language: php

sudo: false

php:
  - 7.2
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - |
    if [[ -z $COMPOSER_FLAGS ]]; then
      composer run test
    else
      composer run phpstan:test
      composer run ecs:test
      composer run phpunit:test
      composer run insights -- --disable-security-check
    fi
